---
- name: Create default directory structure
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '700'
  loop:
    - .cache/nvim/undodir
    - .local/
    - code

- name: Copy dotfiles
  ansible.builtin.copy:
    src: "home/user/{{ item['src'] }}"
    dest: "/home/{{ item['dest'] }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '600'
    directory_mode: '700'
  loop:
    - {src: config/bash, dest: "{{ ansible_user_id }}/.config"}
    - {src: config/fontconfig, dest: "{{ ansible_user_id }}/.config"}
    - {src: config/git, dest: "{{ ansible_user_id }}/.config"}
    - {src: config/npm, dest: "{{ ansible_user_id }}/.config"}
    - {src: config/nvim, dest: "{{ ansible_user_id }}/.config"}
    - {src: config/eza, dest: "{{ ansible_user_id }}/.config"}
    - {src: config/python, dest: "{{ ansible_user_id }}/.config"}
    - {src: rcfiles/gomesrc.sh, dest: "{{ ansible_user_id }}/.gomesrc"}
    - {src: rcfiles/zshrc.sh, dest: "{{ ansible_user_id }}/.zshrc"}

- name: Copy scripts
  ansible.builtin.copy:
    src: home/user/local/bin
    dest: "/home/{{ ansible_user_id }}/.local"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '700'
    directory_mode: '700'

# Instalação de ferramentas padrão
- name: Include basic system tools
  include_tasks: install/apt/default.yml

# Instalação do essencial: Neovim
- name: Include Neovim install
  include_tasks: install/from-gh/install_release.yml
  vars:
    gh_tool_name: Neovim
    gh_tool_repo: https://github.com/neovim/neovim
    gh_tool_version_command: nvim --version | grep -oP 'NVIM \K(v\d+\.\d+\.\d+)'
    gh_tool_final_path: /usr/local/bin/nvim
    gh_tool_download_file_name: nvim-linux64.tar.gz
    gh_tool_extracted_rel_file_path: nvim-linux64/bin/nvim
    gh_tool_symlink_path: /usr/bin/vim
    support_files:
      - { src: "nvim-linux64/share/applications/", dest: "/usr/share/applications/" }
      - { src: "nvim-linux64/share/icons/", dest: "/usr/share/icons/" }
      - { src: "nvim-linux64/share/locale/", dest: "/usr/share/locale/" }
      - { src: "nvim-linux64/share/man/", dest: "/usr/share/man/" }
      - { src: "nvim-linux64/share/nvim/", dest: "/usr/local/share/nvim/" }
      - { src: "nvim-linux64/lib/nvim/", dest: "/usr/local/lib/" }

# Instalação de outras ferramentas via Github
- name: Include Eza install
  include_tasks: install/from-gh/install_release.yml
  vars:
    gh_tool_name: Eza
    gh_tool_repo: https://github.com/eza-community/eza
    gh_tool_version_command: eza --version | grep -oP '^v\d+\.\d+\.\d+'
    gh_tool_final_path: /usr/local/bin/eza
    gh_tool_download_file_name: eza_x86_64-unknown-linux-gnu.tar.gz
    gh_tool_extracted_rel_file_path: eza
    # gh_tool_symlink_path: /usr/bin/ls

- name: Config Eza
  include_tasks: config/eza.yml
  vars:
    eza_theme: rose-pine

- name: Install Neovim
  include_tasks: install/from-gh/install_release.yml
  vars:
    gh_tool_name: Fuzzy Finder
    gh_tool_repo: https://github.com/junegunn/fzf
    gh_tool_version_command: echo -n "v$(fzf --version | grep -oP '^\d+\.\d+\.\d+')"
    gh_tool_final_path: /usr/local/bin/fzf
    gh_tool_download_file_name: fzf-0.57.0-linux_amd64.tar.gz
    gh_tool_extracted_rel_file_path: fzf

- name: Install FdFind
  include_tasks: install/from-gh/install_release.yml
  vars:
    gh_tool_name: FdFind
    gh_tool_repo: https://github.com/sharkdp/fd
    gh_tool_version_command: echo -n "v$(fd --version | grep -oP '^fd\s\K(\d+\.\d+\.\d+)')"
    gh_tool_final_path: /usr/local/bin/fd
    gh_tool_download_file_name: fd-${VERSION}-x86_64-unknown-linux-gnu.tar.gz
    gh_tool_extracted_rel_file_path: fd
    gh_tool_unarchive_options:
      - "--strip-components=1"

- name: Config FZF
  include_tasks: config/fzf.yml

# Instalações únicas
- name: Install kubectl
  include_tasks: install/kubectl.yml

- name: Install Luarocks
  include_tasks: install/luarocks.yml
  vars:
    luarocks_stable_version: "3.11.1"

- name: Install Pyenv
  include_tasks: install/pyenv.yml

- name: Config Pyenv
  include_tasks: config/pyenv.yml

- name: Install NVM
  include_tasks: install/nvm.yml

- name: Config NVM
  include_tasks: config/nvm.yml
