- name: "Install Kubectl"
  block:
    - name: "Get local version"
      ansible.builtin.shell: |
        kubectl version | grep -oP 'Client Version:\s\K(v?\d+\.\d+\.\d+)' || echo ''
      register: local_version
      ignore_errors: true
      changed_when: false

    - name: "Get stable version"
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: true
        validate_certs: true
      register: stable_version
      changed_when: false

    - name: "Set kubectl_stable_version"
      ansible.builtin.set_fact:
        kubectl_stable_version: "{{ stable_version.content | trim }}"
      when: kubectl_stable_version is not defined

    - name: Display versions
      ansible.builtin.debug:
        msg: "Latest kubectl stable version found: {{ kubectl_stable_version }}. Local version found: {{ local_version.stdout | default('None') }}"

    - name: "Installig latest stable version"
      ansible.builtin.shell:
        cmd: |
          set -o pipefail && curl -LO "https://dl.k8s.io/release/{{ kubectl_stable_version }}/bin/linux/amd64/kubectl" &&
          (echo $(curl -sL "https://dl.k8s.io/release/{{ kubectl_stable_version }}/bin/linux/amd64/kubectl.sha256") kubectl | sha256sum --check) &&
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        executable: /bin/bash
      register: ght_installed_version
      changed_when: false
      become: true
      when: local_version.rc != 0 or local_version.stdout != kubectl_stable_version
