# TODO:
# Criar task para garantir keyring e apt.sources
# Criar task para intalar via apt os demais programas, dependentes de keyring
- name: "Check Lens"
  block:
    - name: "Ensure keyrings directory exists with correct permissions"
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
        owner: root
        group: root
      become: true

    - name: "Baixar e dearmor da chave GPG do Lens"
      ansible.builtin.shell:
        cmd: >
          curl -fsSL https://downloads.k8slens.dev/keys/gpg |
          gpg --dearmor -o /usr/share/keyrings/lens-archive-keyring.gpg
        creates: /usr/share/keyrings/lens-archive-keyring.gpg
      become: true

    - name: "Ajustar permissão da chave"
      ansible.builtin.file:
        path: /usr/share/keyrings/lens-archive-keyring.gpg
        mode: '0644'
        owner: root
        group: root
      become: true

    - name: "Add Lens repository with GPG key"
      ansible.builtin.deb822_repository:
        name: lens
        types:
          - deb
        uris: "https://downloads.k8slens.dev/apt/debian"
        architectures:
          - amd64
        suites:
          - stable
        components:
          - main
        signed_by: "/usr/share/keyrings/lens-archive-keyring.gpg"
        state: present
      become: true

    - name: "Install Lens"
      ansible.builtin.apt:
        name: lens
        state: present
        update_cache: true
      become: true
