- name: "Install Luarocks"
  block:
    - name: "Get local version"
      ansible.builtin.shell: |
        luarocks --version | grep -oP 'luarocks\s\K(\d+\.\d+\.\d+)$' || echo ''
      register: local_version
      ignore_errors: true
      changed_when: false

    # - name: "Get stable version"
    #   ansible.builtin.uri:
    #     url: https://luarocks.github.io/luarocks/releases/
    #     return_content: true
    #     validate_certs: true
    #   register: stable_version
    #   changed_when: false

    - name: "Set luarocks_stable_version"
      ansible.builtin.set_fact:
        luarocks_stable_version: "3.11.1"
      when: luarocks_stable_version is not defined

    - name: Display versions
      ansible.builtin.debug:
        msg: "Latest luarocks stable version found: {{ luarocks_stable_version }}. Local version found: {{ local_version.stdout | default('None') }}"

    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: .luarocks
      register: tmp_dir

    - name: Download
      ansible.builtin.get_url:
        url: "https://luarocks.github.io/luarocks/releases/luarocks-{{ luarocks_stable_version }}.tar.gz"
        dest: "{{ tmp_dir.path }}/luarocks.tar.gz"
        validate_certs: true
        mode: "0755"

    - name: "Extract archive"
      ansible.builtin.unarchive:
        src: "{{ tmp_dir.path }}/luarocks.tar.gz"
        dest: "{{ tmp_dir.path }}"
        extra_opts:
          - "--strip-components=1"
        remote_src: true

    - name: "Installig latest stable version"
      ansible.builtin.shell:
        cmd: |
          cd {{ tmp_dir.path }} &&
          ./configure --with-lua-include=/usr/include &&
          make && make install
      args:
        executable: /bin/bash
      changed_when: false
      become: true

- name: Clear
  block:
    - name: "Ensure absent temporary dir"
      ansible.builtin.file:
        path: "{{ tmp_dir.path }}"
        state: absent
      become: true
