- name: "Check NVM"
  block:
    - name: "Get local NVM version"
      ansible.builtin.shell: |
        set -o pipefail &&
        nvm -v | grep -oP '^\K(\d+\.\d+\.\d+)' || echo ''
      register: local_version
      args:
        executable: /bin/bash
      changed_when: false

    - name: "Check NVM latest version"
      ansible.builtin.shell: |
        set -o pipefail && curl -s -D- https://github.com/nvm-sh/nvm/releases/latest |
        grep -oP 'location:.*/tag/v\K(\d+\.\d+\.\d+)'
      args:
        executable: /bin/bash
      register: nvm_latest_version
      changed_when: false

    - name: "Install NVM ({{ nvm_latest_version.stdout }})"
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_latest_version.stdout }}/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      when: local_version.stdout != nvm_latest_version.stdout
