- name: "Check Pyenv"
  block:
    - name: "Get local Pyenv version"
      ansible.builtin.shell: |
        set -o pipefail &&
        pyenv -v | grep -oP '^pyenv\s\K(\d+\.\d+\.\d+)' || echo ''
      register: local_version
      args:
        executable: /bin/bash
      changed_when: false

    - name: "Check Pyenv latest version"
      ansible.builtin.shell: |
        set -o pipefail && curl -s -D- https://github.com/pyenv/pyenv/releases/latest |
        grep -oP 'location:.*/tag/v\K(\d+\.\d+\.\d+)'
      args:
        executable: /bin/bash
      register: pyenv_latest
      changed_when: false

    - name: "Set pyenv_latest_version"
      ansible.builtin.set_fact:
        pyenv_latest_version: "{{ pyenv_latest.stdout | trim }}"
      when: pyenv_latest_version is not defined

    - name: Display versions
      ansible.builtin.debug:
        msg: "Latest pyenv latest version found: {{ pyenv_latest_version }}. Local version found: {{ local_version.stdout | default('None') }}"

- name: "Install Pyenv"
  when: local_version.stdout != pyenv_latest_version
  block:
    - name: "Ensure pyenv directory exists"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/pyenv"
        state: directory
        mode: "0755"
      register: pyenv_dir

    - name: "Clone or update pyenv repository"
      ansible.builtin.git:
        repo: "https://github.com/pyenv/pyenv.git"
        dest: "{{ pyenv_dir.path }}"
        version: "v{{ pyenv_latest_version }}"
        update: true

    - name: "Ensure Pyenv symbolic link"
      ansible.builtin.file:
        src: "{{ pyenv_dir.path }}/bin/pyenv"
        dest: "/usr/local/bin/pyenv"
        state: link
        force: true
      become: true
