- name: "Ensure configs"
  block:
    - name: "Ensure theme"
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/.config/eza/themes/{{ eza_theme | default('default') }}.yml"
        dest: "{{ ansible_env.HOME }}/.config/eza/theme.yml"
        state: link
        force: true

    - name: "Display Theme"
      ansible.builtin.debug:
        msg: "Eza theme setted: {{ eza_theme | default('default') }}"
