- name: "Ensure nvm configs"
  block:
    - name: "Check default version"
      ansible.builtin.shell:
        cmd: |
          set -o pipefail &&
          source {{ ansible_facts['env'].HOME }}/.nvm/nvm.sh &&
          nvm ls --no-colors 2>/dev/null | grep -oP '^default\s\->\s\K(v\d+\.\d+\.\d+)' || echo ''
      args:
        executable: /bin/zsh
      register: current_default_version
      changed_when: false

    - name: "Set desired default Node version"
      ansible.builtin.set_fact:
        default_node_version: "v20.18.1"
      when: default_node_version is not defined

    - name: "Install and configure Node default version ({{ default_node_version }})"
      ansible.builtin.shell:
        cmd: |
          source {{ ansible_facts['env'].HOME }}/.nvm/nvm.sh &&
          nvm install "{{ default_node_version }}" &&
          nvm alias default "{{ default_node_version }}"
      args:
        executable: /bin/bash
      changed_when: false
      when: current_default_version.stdout != default_node_version

    - name: "Set desired global npm packages"
      ansible.builtin.set_fact:
        npm_global_packages: "{{ npm_global_packages | default(['tree-sitter-cli']) }}"

    - name: "Install global npm packages ({{ default_node_version }})"
      ansible.builtin.shell:
        cmd: |
          source {{ ansible_facts['env'].HOME }}/.nvm/nvm.sh &&
          nvm use default >/dev/null 2>&1 &&
          npm ls -g --depth=0 "{{ item }}" >/dev/null 2>&1 || npm install -g "{{ item }}"
      args:
        executable: /bin/bash
      loop: "{{ npm_global_packages }}"
      register: npm_global_install
      changed_when: "'added' in npm_global_install.stdout"
