[general]
abbreviate-tab-names=false
background-image-file='/home/gomes/Pictures/terminal-background/coffee-shop.jpg'
background-image-layout-mode=0
compat-delete='delete-sequence'
copy-on-select=true
default-shell='/usr/bin/zsh'
display-n=0
display-tab-names=0
gtk-use-system-default-theme=true
hide-tabs-if-one-tab=false
history-size=1000
load-guake-yml=true
max-tab-name-length=100
mouse-display=true
open-tab-cwd=true
prompt-on-quit=true
quick-open-command-line='nvim %(file_path)s'
quick-open-enable=true
restore-tabs-notify=true
restore-tabs-startup=true
save-tabs-when-changed=true
schema-version='3.9.0'
scroll-keystroke=true
start-at-login=true
use-default-font=false
use-popup=true
use-scrollbar=true
use-trayicon=true
window-halignment=2
window-height=96
window-horizontal-displacement=0
window-losefocus=false
window-refocus=false
window-tabbar=true
window-width=50

[keybindings/global]
show-hide='F12'

[keybindings/local]
close-tab='disabled'
decrease-height='<Primary>Down'
decrease-transparency='<Primary><Shift>Down'
increase-height='<Primary>Up'
increase-transparency='<Primary><Shift>Up'
next-tab='<Primary><Shift>Right'
previous-tab='<Primary><Shift>Left'

[style/background]
transparency=85

[style/font]
allow-bold=true
palette='#34341A1A0D0D:#9B9B28281B1B:#626261613232:#C2C26E6E2727:#51515B5B5C5C:#9B9B1D1D2929:#585880805656:#F6F6D7D75C5C:#878742422727:#FFFF42423030:#B3B3B1B16363:#FFFF95956565:#9E9EB2B2B3B3:#FFFF5B5B6A6A:#8989CCCC8E8E:#FFFFE5E59797:#F6F6D5D56A6A:#11110B0B0D0D'
palette-name='Mona Lisa'
style='Hack Nerd Font Mono 12'
