- name: "Check installed and latest versions [{{ gh_tool_name }}]"
  block:
    - name: "Check if installed [{{ gh_tool_name }}]"
      ansible.builtin.stat:
        path: "{{ gh_tool_final_path }}"
      register: ght_stat

    - name: "Get version [{{ gh_tool_name }}]"
      ansible.builtin.shell: set -o pipefail && {{ gh_tool_version_command }}
      args:
        executable: /bin/bash
      changed_when: false
      register: ght_installed_version
      when: ght_stat.stat.exists

    - name: "Set gh_tool_url_version_command [{{ gh_tool_name }}]"
      ansible.builtin.set_fact:
        gh_tool_url_version_command: "grep -oP 'location:.*/tag/\\K(v?\\d+\\.\\d+\\.\\d+)'"
      when: gh_tool_url_version_command is not defined

    - name: "Check latest [{{ gh_tool_name }}]"
      ansible.builtin.shell: |
        set -o pipefail && curl -s -D- {{ gh_tool_repo }}/releases/latest |
        {{ gh_tool_url_version_command }}
      args:
        executable: /bin/bash
      register: ght_latest_version
      changed_when: false

    - name: "Display versions [{{ gh_tool_name }}]"
      ansible.builtin.debug:
        msg: "Latest version found: {{ ght_latest_version.stdout }}. Local version found: {{ ght_installed_version.stdout | default('None') }}"
      when: not(ght_installed_version is not skipped and ght_installed_version.stdout == ght_latest_version.stdout)

    - name: "Compare versions [{{ gh_tool_name }}]"
      ansible.builtin.debug:
        msg: "{{ gh_tool_name }} present and up to date (Version {{ ght_latest_version.stdout }})."
      when: ght_installed_version is not skipped and ght_installed_version.stdout == ght_latest_version.stdout

- name: "Check for updates [{{ gh_tool_name }}]"
  when: not(ght_installed_version is not skipped and ght_installed_version.stdout == ght_latest_version.stdout)
  block:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: .gh_tool
      register: tmp_dir

    - name: "Download  archive [{{ gh_tool_name }}]"
      ansible.builtin.get_url:
        url: "{{ gh_tool_repo }}/releases/latest/download/{{ gh_tool_download_file_name | regex_replace('\\$\\{VERSION\\}', ght_latest_version.stdout) }}"
        dest: "{{ tmp_dir.path }}/gh_tool.tar.gz"
        validate_certs: false  # TODO: Checar certs
        mode: "0755"

    - name: "Extract archive [{{ gh_tool_name }}]"
      ansible.builtin.unarchive:
        src: "{{ tmp_dir.path }}/gh_tool.tar.gz"
        dest: "{{ tmp_dir.path }}"
        extra_opts: "{{ gh_tool_unarchive_options | default([]) }}"
        remote_src: true

    - name: "Install executable [{{ gh_tool_name }}]"
      ansible.builtin.command: "install -Dm 0755 {{ tmp_dir.path }}/{{ gh_tool_extracted_rel_file_path }} {{ gh_tool_final_path }}"
      changed_when: false
      become: true

    - name: "Ensure support dirs [{{ gh_tool_name }}]"
      ansible.builtin.file:
        path: "{{ item.dest }}"
        state: directory
        mode: "{{ item.mode | default('0755') }}" # Valor padrão para mode
      loop: "{{ support_files }}"
      loop_control:
        label: "{{ item.dest }}"
      become: true
      when: support_files is defined

    - name: "Copy support files [{{ gh_tool_name }}]"
      ansible.builtin.copy:
        src: "{{ tmp_dir.path }}/{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('0755') }}" # Valor padrão para mode
        remote_src: true
      loop: "{{ support_files }}"
      loop_control:
        label: "{{ item.src }} -> {{ item.dest }}"
      become: true
      when: support_files is defined

- name: "Ensure symbolic links [{{ gh_tool_name }}]"
  block:
    - name: "Ensure symbolic link for [{{ gh_tool_name }}]"
      ansible.builtin.file:
        src: "{{ gh_tool_final_path }}"
        dest: "{{ gh_tool_symlink_path }}"
        state: link
        force: true
      become: true
      when: gh_tool_symlink_path is defined
